server:
  port: 8800

spring:
  application:
    name: kg-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka